//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DtDc_Billing.Entity_FR
{
    using System;
    using System.Collections.Generic;
    
    public partial class addcodamount
    {
        public int am_id { get; set; }
        public string chequeno { get; set; }
        public string bank_name { get; set; }
        public string branch { get; set; }
        public string consinment_no { get; set; }
        public string Invoiceno { get; set; }
    }
}
