//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DtDc_Billing.Entity_FR
{
    using System;
    using System.Collections.Generic;
    
    public partial class addtopayamount
    {
        public int ad_id { get; set; }
        public string sapno { get; set; }
        public string consinmentno { get; set; }
        public string date { get; set; }
        public string Invoiceno { get; set; }
    }
}
