//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DtDc_Billing.Entity_FR
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoxEnvelopePacking
    {
        public int B_id { get; set; }
        public Nullable<System.DateTime> Entrydate { get; set; }
        public string pfcode { get; set; }
        public Nullable<int> Userid { get; set; }
        public string Type { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<double> Amount { get; set; }
    }
}
