//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DtDc_Billing.Entity_FR
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditNote
    {
        public int Cr_id { get; set; }
        public Nullable<double> Cr_Amount { get; set; }
        public Nullable<System.DateTime> cr_date { get; set; }
        public string tempch_date { get; set; }
        public string Invoiceno { get; set; }
    }
}
