//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DtDc_Billing.Entity_FR
{
    using System;
    using System.Collections.Generic;
    
    public partial class deliverydata
    {
        public int d_id { get; set; }
        public string consinmentno { get; set; }
        public Nullable<System.DateTime> delivered_date { get; set; }
        public Nullable<System.DateTime> delivered_time { get; set; }
        public string receivedby { get; set; }
        public string remarks { get; set; }
        public string tempdelivereddate { get; set; }
        public string tempdeliveredtime { get; set; }
    }
}
