//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DtDc_Billing.Entity_FR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Destination
    {
        public long Dest_Id { get; set; }
        public string Pincode { get; set; }
        public string Name { get; set; }
        public string State_ { get; set; }
        public Nullable<int> CITY_ID { get; set; }
        public string ZONE { get; set; }
        public string LANE { get; set; }
        public string GECLANE { get; set; }
    }
}
