//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DtDc_Billing.Entity_FR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dtdc_Ptp
    {
        public int ptp_id { get; set; }
        public string dest { get; set; }
        public Nullable<double> PUpto500gm { get; set; }
        public Nullable<double> PAdd500gm { get; set; }
        public Nullable<double> PU10to25kg { get; set; }
        public Nullable<double> PU25to50 { get; set; }
        public Nullable<double> PU50to100 { get; set; }
        public Nullable<double> Padd100kg { get; set; }
        public Nullable<double> P2Upto500gm { get; set; }
        public Nullable<double> P2Add500gm { get; set; }
        public Nullable<double> P2U10to25kg { get; set; }
        public Nullable<double> P2U25to50 { get; set; }
        public Nullable<double> P2U50to100 { get; set; }
        public Nullable<double> P2add100kg { get; set; }
        public string Company_id { get; set; }
        public Nullable<int> Sector_Id { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Sector Sector { get; set; }
    }
}
