//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DtDc_Billing.Entity_FR
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtdcPlu
    {
        public int plus_id { get; set; }
        public string destination { get; set; }
        public Nullable<double> Upto500gm { get; set; }
        public Nullable<double> U10to25kg { get; set; }
        public Nullable<double> U25to50 { get; set; }
        public Nullable<double> U50to100 { get; set; }
        public Nullable<double> add100kg { get; set; }
        public Nullable<double> go149 { get; set; }
        public Nullable<double> go99 { get; set; }
        public string Company_id { get; set; }
        public Nullable<double> Add500gm { get; set; }
        public Nullable<int> Sector_Id { get; set; }
        public Nullable<bool> CashCounterPlus { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Company Company1 { get; set; }
        public virtual Sector Sector { get; set; }
    }
}
