//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DtDc_Billing.Entity_FR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dtdc_Ecommerce
    {
        public int Ecom_id { get; set; }
        public Nullable<double> PUpto500gm { get; set; }
        public Nullable<double> PAdd500gm { get; set; }
        public Nullable<double> PAdd5kg { get; set; }
        public Nullable<double> GEUpto500gm { get; set; }
        public Nullable<double> GEAdd500gm { get; set; }
        public Nullable<double> GEAdd5kg { get; set; }
        public string Company_id { get; set; }
        public Nullable<int> Sector_Id { get; set; }
        public Nullable<double> PAdditionalPerKG { get; set; }
        public Nullable<double> GEAdditionalPerKG { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Company Company1 { get; set; }
        public virtual Sector Sector { get; set; }
    }
}
