//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DtDc_Billing.Entity_FR
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailPromotion
    {
        public int eid { get; set; }
        public string s_mail { get; set; }
        public string s_pass { get; set; }
        public string image1 { get; set; }
        public string subject { get; set; }
        public string message { get; set; }
        public string note { get; set; }
    }
}
