//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DtDc_Billing.Entity_FR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Emp_Id { get; set; }
        public string Emp_Name { get; set; }
        public string email { get; set; }
        public Nullable<long> Phone { get; set; }
        public string PF_Code { get; set; }
        public string Emp_Role { get; set; }
        public string E_Password { get; set; }
    
        public virtual Franchisee Franchisee { get; set; }
    }
}
