//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DtDc_Billing.Entity_FR
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpiredStationary
    {
        public long Ex_Id { get; set; }
        public string Consignment_no { get; set; }
        public Nullable<System.DateTime> Expiry_Date { get; set; }
        public string Expiry_Exceded { get; set; }
        public Nullable<int> days { get; set; }
    }
}
