//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DtDc_Billing.Entity_FR
{
    using System;
    using System.Collections.Generic;
    
    public partial class express_cargo
    {
        public int Exp_Id { get; set; }
        public Nullable<double> Exslab1 { get; set; }
        public Nullable<double> Exslab2 { get; set; }
        public Nullable<double> Upto { get; set; }
        public string Company_id { get; set; }
        public Nullable<int> Sector_Id { get; set; }
        public Nullable<bool> CashCounterExpr { get; set; }
    
        public virtual Sector Sector { get; set; }
    }
}
