//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DtDc_Billing.Entity_FR
{
    using System;
    using System.Collections.Generic;
    
    public partial class GECrate
    {
        public long GECrateId { get; set; }
        public Nullable<double> Slab1 { get; set; }
        public Nullable<double> Slab2 { get; set; }
        public Nullable<double> Slab3 { get; set; }
        public Nullable<double> Slab4 { get; set; }
        public Nullable<double> Uptosl1 { get; set; }
        public Nullable<double> Uptosl2 { get; set; }
        public Nullable<double> Uptosl3 { get; set; }
        public Nullable<double> Uptosl4 { get; set; }
        public string Company_id { get; set; }
        public Nullable<int> NoOfSlab { get; set; }
        public Nullable<int> Sector_Id { get; set; }
        public Nullable<long> GECSectorId { get; set; }
        public string SectorName { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual GECSector GECSector { get; set; }
        public virtual Sector Sector { get; set; }
    }
}
