//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DtDc_Billing.Entity_FR
{
    using System;
    using System.Collections.Generic;
    
    public partial class GECSector
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GECSector()
        {
            this.GECrates = new HashSet<GECrate>();
        }
    
        public long GECSectorId { get; set; }
        public string SectorName { get; set; }
        public string Pf_code { get; set; }
        public string Pincode { get; set; }
        public Nullable<int> Priority { get; set; }
        public string City { get; set; }
    
        public virtual Franchisee Franchisee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GECrate> GECrates { get; set; }
    }
}
