//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DtDc_Billing.Entity_FR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Holiday
    {
        public long Holiday_ID { get; set; }
        public Nullable<int> H_Year { get; set; }
        public string State { get; set; }
        public string H_Month { get; set; }
        public Nullable<System.DateTime> H_datetime { get; set; }
        public string Holiday_Name { get; set; }
    }
}
