//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DtDc_Billing.Entity_FR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Issue
    {
        public int Issue_id { get; set; }
        public string startno { get; set; }
        public string endno { get; set; }
        public Nullable<int> noofleafs { get; set; }
        public string Inssuedate { get; set; }
        public string Comapny_Id { get; set; }
        public string EmployeeName { get; set; }
        public string Pf_code { get; set; }
    }
}
