//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DtDc_Billing.Entity_FR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nondox
    {
        public int Non_ID { get; set; }
        public Nullable<double> Aslab1 { get; set; }
        public Nullable<double> Aslab2 { get; set; }
        public Nullable<double> Aslab3 { get; set; }
        public Nullable<double> Aslab4 { get; set; }
        public Nullable<double> Sslab1 { get; set; }
        public Nullable<double> Sslab2 { get; set; }
        public Nullable<double> Sslab3 { get; set; }
        public Nullable<double> Sslab4 { get; set; }
        public Nullable<double> AUptosl1 { get; set; }
        public Nullable<double> AUptosl2 { get; set; }
        public Nullable<double> AUptosl3 { get; set; }
        public Nullable<double> AUptosl4 { get; set; }
        public Nullable<double> SUptosl1 { get; set; }
        public Nullable<double> SUptosl2 { get; set; }
        public Nullable<double> SUptosl3 { get; set; }
        public Nullable<double> SUptosl4 { get; set; }
        public Nullable<int> Sector_Id { get; set; }
        public string Company_id { get; set; }
        public Nullable<int> NoOfSlabN { get; set; }
        public Nullable<int> NoOfSlabS { get; set; }
        public Nullable<bool> CashCounterNon { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Company Company1 { get; set; }
        public virtual Sector Sector { get; set; }
    }
}
