//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DtDc_Billing.Entity_FR
{
    using System;
    using System.Collections.Generic;
    
    public partial class pincodeZone
    {
        public long PincodeZoneId { get; set; }
        public string PINCODE { get; set; }
        public string BR_CITY { get; set; }
        public string STATE { get; set; }
        public string GEC_LANE { get; set; }
        public string B2C_AND_B2B { get; set; }
        public Nullable<System.DateTime> Date_Times { get; set; }
        public string Status { get; set; }
    }
}
