//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DtDc_Billing.Entity_FR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Priority
    {
        public int pri_id { get; set; }
        public Nullable<double> prislab1 { get; set; }
        public Nullable<double> prislab2 { get; set; }
        public Nullable<double> prislab3 { get; set; }
        public Nullable<double> prislab4 { get; set; }
        public Nullable<int> Sector_Id { get; set; }
        public Nullable<double> priupto1 { get; set; }
        public Nullable<double> priupto2 { get; set; }
        public Nullable<double> priupto3 { get; set; }
        public Nullable<double> priupto4 { get; set; }
        public string Company_id { get; set; }
        public Nullable<int> prinoofslab { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Sector Sector { get; set; }
    }
}
