//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DtDc_Billing.Entity_FR
{
    using System;
    using System.Collections.Generic;
    
    public partial class RaiseQuery
    {
        public int RaiseQueries_ID { get; set; }
        public string RaiseQueries_Description { get; set; }
        public Nullable<int> RaiseQueries_Status { get; set; }
        public Nullable<System.DateTime> RaiseQueries_datetime { get; set; }
        public string RaiseQueries_Name { get; set; }
        public string Domain_Name { get; set; }
        public string Pf_code { get; set; }
    }
}
