//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DtDc_Billing.Entity_FR
{
    using System;
    using System.Collections.Generic;
    
    public partial class RaiseIssue
    {
        public int RaiseIssue_ID { get; set; }
        public string RaiseIssue_ScreenShotFile { get; set; }
        public string RaiseIssue_Description { get; set; }
        public Nullable<int> RaiseIssue_Status { get; set; }
        public Nullable<System.DateTime> RaiseIssue_datetime { get; set; }
        public string RaiseIssue_Name { get; set; }
        public string Domain_Name { get; set; }
        public string RaiseIssue_FileName { get; set; }
    }
}
