//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DtDc_Billing.Entity_FR
{
    using System;
    using System.Collections.Generic;
    
    public partial class RedeemOtp
    {
        public long Otp_Id { get; set; }
        public string Otp { get; set; }
        public string Mobile_No { get; set; }
        public Nullable<bool> verified { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
        public Nullable<System.DateTime> Datetime_Redeem { get; set; }
    }
}
