//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DtDc_Billing.Entity_FR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sector
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sector()
        {
            this.Dtdc_Ecommerce = new HashSet<Dtdc_Ecommerce>();
            this.Dtdc_Ptp = new HashSet<Dtdc_Ptp>();
            this.dtdcPlus = new HashSet<dtdcPlu>();
            this.express_cargo = new HashSet<express_cargo>();
            this.GECrates = new HashSet<GECrate>();
            this.NewDtdc_Ecommerce = new HashSet<NewDtdc_Ecommerce>();
            this.Nondoxes = new HashSet<Nondox>();
            this.Priorities = new HashSet<Priority>();
            this.RateLaptops = new HashSet<RateLaptop>();
            this.Ratems = new HashSet<Ratem>();
            this.RateRevLaptops = new HashSet<RateRevLaptop>();
        }
    
        public int Sector_Id { get; set; }
        public string Sector_Name { get; set; }
        public string Pf_code { get; set; }
        public string Pincode_values { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<bool> CashD { get; set; }
        public Nullable<bool> CashN { get; set; }
        public Nullable<bool> BillD { get; set; }
        public Nullable<bool> BillN { get; set; }
        public Nullable<bool> GEcreate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dtdc_Ecommerce> Dtdc_Ecommerce { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dtdc_Ptp> Dtdc_Ptp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtdcPlu> dtdcPlus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<express_cargo> express_cargo { get; set; }
        public virtual Franchisee Franchisee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GECrate> GECrates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NewDtdc_Ecommerce> NewDtdc_Ecommerce { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nondox> Nondoxes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Priority> Priorities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RateLaptop> RateLaptops { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ratem> Ratems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RateRevLaptop> RateRevLaptops { get; set; }
    }
}
