//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DtDc_Billing.Entity_FR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service_list
    {
        public long Service_Id { get; set; }
        public string Pincode { get; set; }
        public string Service_ { get; set; }
        public string Pf_Code { get; set; }
    }
}
