//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DtDc_Billing.Entity_FR
{
    using System;
    using System.Collections.Generic;
    
    public partial class wallet_History
    {
        public long H_Id { get; set; }
        public string H_Status { get; set; }
        public Nullable<long> User_Id { get; set; }
        public string PF_Code { get; set; }
        public Nullable<long> Receipt_Id { get; set; }
        public string consignment_no { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
        public string mobile_no { get; set; }
    
        public virtual Franchisee Franchisee { get; set; }
        public virtual User User { get; set; }
    }
}
